### ISSUE TITLE
Archivo .gitignore

### ISSUE THREAD

**Issue by aespinosav** [computo-fc/metodos_rigurosos#25]
Hola, podrían quitar el archivo .gitignore del repositorio y dejar de seguirlo, para que cuando hagamos pulls cada quien se quede con su .gitignore ??

Es que cada vez que hago pulls, me cambia el .gitignore
Gracias,
Alonso

**Comment by lbenet** [comment]
Lo tomaré en cuenta para la próxima que haga un merge. Cierro entonces esto.
